# Swagger MCP Server Configuration

# List of Swagger/OpenAPI sources
sources:
  # Example: Local file source (we'll create this for testing)
  - name: "local-example"
    source: "./test/example-swagger.json"
    description: "Local example API"
    tags: ["local", "example"]

  - name: "test"
    source: "https://api.apis.guru/v2/specs/6-dot-authentiqio.appspot.com/6/openapi.json"
    description: "Authentiqio API"

# Search configuration
search:
  fuzzyThreshold: 0.6
  maxResults: 20
